# Use Node.js configuration.
language: node_js

node_js:
  - 10
  - 12
  - node # latest

os:
  - linux
  - osx
  - windows

script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm test; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run test:windows; fi
  - npm run lint
